### ISSUE TITLE
why did i find an error message like this

### ISSUE THREAD

**Issue by filus3421** [JamalKheirBeik/real-estate#2]
<img width="960" alt="kos2" src="https://user-images.githubusercontent.com/105200098/167404778-d14a640d-66c9-474a-b1e8-524a2badc193.png">

where is wrong?

**Comment by jamalkheirbeik** [comment]
The database i provided is empty you need to go to the admin page and enter some data (properties, locations) in order for it to be shown.
If you want to access the admin page just add "/admin" at the end of the basic URL.
Also don't forget to change the database name when you import it to your phpmyadmin dashboard because you will get an error since you have a different name on the connection.php file.

**Comment by filus3421** [comment]
I can login as admin but I want to add a property but it still shows an error like this?

I use xampp for ftp and have created the user.

<img width="730" alt="xamp2" src="https://user-images.githubusercontent.com/105200098/167538902-45b7e758-515c-40bc-bbff-b248fd25d3c8.png">

**Comment by jamalkheirbeik** [comment]
Did you configure the ftp_config.php file?
If that didn't work you can try to use the php move_uploaded_file function instead of the ftp method to move the images to their specific folder.
Check this link for more info on how to use the function: https://www.php.net/manual/en/function.move-uploaded-file.php

**Comment by filus3421** [comment]
i have configured ftp , but is there something wrong with this code ?

<img width="466" alt="ftp erorr" src="https://user-images.githubusercontent.com/105200098/167750130-607f033c-baaa-41d8-93dd-b52dab5a63f6.png">


<img width="452" alt="ftp erorr 2" src="https://user-images.githubusercontent.com/105200098/167750150-a81109cd-c6a3-4306-bfdf-9685c41a9600.png">

I've also tried using hosting but still experiencing the same thing

**Comment by jamalkheirbeik** [comment]
The code is fine this is the same code as the live version.
You probably have a typo or something.
